esphome:
  name: infrared

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret api_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Infrared Fallback Hotspot"
    password: "qY6KU4zF7O4U"

captive_portal:
    
remote_receiver:
  pin:
    number: D4
    inverted: True
    mode: INPUT_PULLUP
  dump: lg
