esphome:
  name: templivingroom

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret api_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Templivingroom Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal: {}

i2c:
  sda: 4
  scl: 5
  scan: true

sensor:
  - platform: aht10
    temperature:
      name: "Living Room Temperature"
      filters:
        - calibrate_linear:
          - 0.0 -> 0.0
          - 23.67 -> 19.9
    humidity:
      name: "Living Room Humidity"
      filters:
        - calibrate_linear:
          - 0.0 -> 0.0
          - 31.23 -> 43

    update_interval: 60s

        
